### PR TITLE
Adding required options to hyperswarm

### PR DESCRIPTION
**Pull request by martinheidegger**
In gitter channel it was mentioned that those properties are required.

### CODE REVIEW

**Comment by martinheidegger** [comment]
When rebuilding I noticed that the built files have been outdated.

**Comment by martinheidegger** [comment]
Thanks @okdistribute

**Comment by hackergrrl** [comment]
Thanks @martinheidegger!

**Comment by jes** [comment]
I think the latest version of mutlifeed actually *doesn't* want hypercore as the first argument! See docs at https://github.com/kappa-db/multifeed
I suspect the problem here was that the text of the tutorial was referring to a new-ish version of multifeed but the package.json pulled in an older version.

**Pull request merged**
