### PR TITLE
html to md links

### PR DESCRIPTION
**Pull request by DougAnderson444**
When I try to use these links in Github the links break because of html/md difference

I know the original workshop was hosted on noffle, but I presume this is now hosted on Github

If so, these changes make sense. If not, feel free to discard...

### CODE REVIEW

**Comment by hackergrrl** [comment]
The links seem to work fine for me:
https://kappa-db.github.io/workshop/build/01.html

Are you looking at it from somewhere else?

**Comment by DougAnderson444** [comment]
I was clicking on them in the [github code pages](https://github.com/kappa-db/workshop/blob/master/problems/01.md).

Such a great workshop to go through! I made some fixes, enhancements, etc. if you want to ad them.

**Comment by DougAnderson444** [comment]
I see what was happening, the readme was taking you to the old noffle site. I've [commited](https://github.com/kappa-db/workshop/pull/28/commits/91bb97823753f74d81b84b61182d629955e3c792) a change to reflect the new github.io subdomain and reverted the `.md` changes

**Comment by ralphtheninja** [comment]
I don't like these changes. They are all over the place and I don't see the value of replacing single quote strings with double quotes.

**Comment by DougAnderson444** [comment]
Closing

**Pull request closed without merging**
